apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  imagePullSecrets:
  - name: ecr-secret  
  containers:
  - name: mysql
    image: 011926502057.dkr.ecr.us-east-1.amazonaws.com/vipinecr/my_db:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
