apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp-namespace
  labels:
    app: employees  
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: employees  
  template:
    metadata:
      labels:
        app: employees  
    spec:
      containers:
      - name: webapp
        image: 011926502057.dkr.ecr.us-east-1.amazonaws.com/vipinecr/my_app@sha256:c379ffe362f2858959e9d4f36caa96c5174e80bbc2961b08e2534604a2ad658c
        ports:
        - containerPort: 8080
        command: ["python3", "app.py"]
        env:
        - name: DBHOST
          value: "mysql-service.mysql-namespace"  
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "pw"
