apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-namespace  
spec:
  type: NodePort
  selector:
    app: webapp-deployment  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  
