apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp-namespace  
  labels:
    app: employee
spec:
  imagePullSecrets:  
    - name: ecr-secret
  containers:
  - name: webapp
    image: 011926502057.dkr.ecr.us-east-1.amazonaws.com/vipinecr/my_app:latest
    ports:
    - containerPort: 8080
    command: ["python3", "app.py"]
    env:
    - name: DBHOST
      value: "mysql-service.mysql-namespace"  
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DATABASE
      value: "employees"
    - name: DBPWD
      value: "pw"
